library(sf)
library(rgdal)
library(dplyr)
library(plyr)
library(readr)
library(raster)
library(bcmaps)
library(bcdata)
library(fasterize)
library(tidyr)
library(rio)
library(WriteXLS)
library(ggplot2)
library(readxl)
library(stringr)
library(mapview)
library(gdata)
library(reshape2)
library(stars)
library(exactextractr)


#added by Gen P.
library(plotKML)
library(purrr)
library(lubridate)
library(tibble)
library(janitor)
library(foreign)
library(SpatialTools)
library(magrittr)
library(spdep)
library(ggnewscale)
library(exactextractr)

